import React from 'react';
import { Link } from 'react-router-dom';

export function TermsPage() {
    return (
        <div className="min-h-screen bg-zinc-950 text-zinc-300 font-sans overflow-x-hidden">
            <nav className="fixed top-0 left-0 right-0 z-50 bg-zinc-950/80 backdrop-blur-xl border-b border-white/5">
                <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
                    <Link to="/" className="flex items-center gap-2.5 hover:opacity-80 transition-opacity">
                        <img src="/logo.png" alt="Split-Ledger Logo" className="h-8 object-contain" />
                    </Link>
                </div>
            </nav>
            <main className="pt-32 pb-24 max-w-3xl mx-auto px-6">
                <h1 className="text-4xl font-extrabold text-white mb-4 tracking-tight">Terms of Service</h1>
                <p className="text-zinc-500 mb-10">Last Updated: {new Date().toLocaleDateString()}</p>

                <div className="space-y-8 text-sm leading-relaxed text-zinc-400">
                    <section>
                        <p className="text-lg text-zinc-300 font-medium">
                            By registering a workspace on Split-Ledger, you agree to be bound by the following comprehensive Terms of Service. These terms govern your utilization of our API, infrastructure, and billing integration.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">1. Provision of Services</h2>
                        <p>
                            Split-Ledger provides "Backend-as-a-Service" infrastructure designed for multi-tenant micro-SaaS applications. This includes schema provisioning, API key issuance, webhook dispatching, and automated billing synchronization via Stripe Connect. We reserve the right to modify, suspend, or discontinue the Service immediately if usage violates these conditions or initiates targeted abuse on the platform.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">2. Account Registration and Tenant Responsibility</h2>
                        <p>
                            Upon creating a workspace, you are granted a non-transferable right to use the generated `sk_live_*` API keys. You are strictly responsible for maintaining the absolute secrecy of these keys. Split-Ledger accepts zero liability for data breaches, financial loss, or unauthorized access resulting from leaked API keys or compromised JWT tokens generated by your integrations.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">3. Commission-Based Pricing and Billing</h2>
                        <p>
                            Split-Ledger primarily operates on a revenue-share and usage metering model. By connecting your Stripe account to our platform, you explicitly authorize Split-Ledger to automatically withhold the agreed-upon platform fee (e.g., 20% or custom enterprise rate) at the exact moment of transaction capture using Stripe Connect Destination Charges.
                        </p>
                        <p className="mt-2">
                            For free-tier and sandbox environments, platform usage is completely free up to designated API thresholds (e.g. 10,000 requests/month). Going beyond limits on the free tier involves a hard-cut off unless upgraded to a production plan.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">4. Acceptable Use and Rate Limiting</h2>
                        <p>You agree NOT to use the Split-Ledger API to:</p>
                        <ul className="list-disc pl-6 mt-4 space-y-2">
                            <li>Process illicit, illegal, or highly governed transactions without proper legal licensing.</li>
                            <li>Attempt to exploit, scan, or reverse engineer the multi-tenant isolation layer.</li>
                            <li>DDoS or deliberately overwhelm the Redis queuing infrastructure or webhook dispatcher.</li>
                        </ul>
                        <p className="mt-4">
                            Split-Ledger enforces strict sliding-window rate limiting on all endpoints. Repeated 429 errors resulting from abusive integration loops will result in automatic IP bans and temporary tenant suspension.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">5. Webhook Data Integrity</h2>
                        <p>
                            Split-Ledger guarantees the cryptographic signing of all outbound webhooks via a secret HMAC key provided in your dashboard. It is strictly your responsibility to verify the `X-Signature` header of incoming payload requests. Split-Ledger is not responsible for malicious actions taken entirely outside our ecosystem by threat actors interacting with your insecurely configured receiving endpoints.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">6. Limitation of Liability and SLAs</h2>
                        <p>
                            IN NO EVENT SHALL SPLIT-LEDGER OR ITS SUPPLIERS BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL, OR PUNITIVE DAMAGES WHATEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR INABILITY TO USE THE INFRASTRUCTURE, EVEN IF SUPERVISED.
                        </p>
                        <p className="mt-2">
                            Service Level Agreements (SLAs) dictating 99.99% uptime guarantees are exclusively reserved for "Enterprise" tier customers executing a signed Master Service Agreement (MSA).
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4">7. Termination</h2>
                        <p>
                            We may terminate or suspend your tenant workspace immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease and all queued webhooks will be flushed.
                        </p>
                    </section>
                </div>
            </main>
        </div>
    );
}

export default TermsPage;
